In [84]:
from astroquery.heasarc import Heasarc, Conf
import astropy.units as u
import numpy as np

In [103]:
object_name = "Cyg X-1"

# setup server (see https://astroquery.readthedocs.io/en/latest/heasarc/heasarc.html?highlight=INTEGRAL#using-alternative-heasarc-servers)
integral_query = Heasarc()
Conf.server.set('https://www.isdc.unige.ch/browse/w3query.pl')

query_dict= {}
# mission name (see https://astroquery.readthedocs.io/en/latest/heasarc/heasarc.html?highlight=INTEGRAL#using-alternative-heasarc-servers)
query_dict["mission"] = "integral_rev3_scw"
# object_name
query_dict["object_name"] = object_name
# Sort the table according to one of the Columns
query_dict["sortvar"] = "START_DATE"
# max number of results returned (0=unendlich)
query_dict["resultmax"] = 0
# for all possible input in query_dict see https://astroquery.readthedocs.io/en/latest/heasarc/heasarc.html

r = integral_query.query_object(**query_dict)
# convert bytestrings to unicode - makes it easier to use in the following
r.convert_bytestring_to_unicode()
# convert from astropy table to pandas - easier to use
p = r.to_pandas()

int_cols = ["OBS_ID"]
p["START_DATE"] = pd.to_datetime(p["START_DATE"], errors="coerce")
# flt_cols = ["RA_X", "DEC_X", "_SEARCH_OFFSET"]
# p[flt_cols] = pd.to_numeric(p[flt_cols].stack(), errors="coerce").unstack()

WARNING: UnitsWarning: 'ISO' did not parse as fits unit: At col 0, Unit 'ISO' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]

In [106]:
p["START_DATE"]

0       2002-11-16 20:06:11
1       2002-11-16 20:16:53
2       2002-11-16 20:18:23
3       2002-11-16 20:55:43
4       2002-11-16 21:53:21
                ...
19161   2022-05-16 13:17:35
19162   2022-05-16 14:13:10
19163   2022-05-16 14:15:05
19164   2022-05-16 15:10:39
19165   2022-05-16 15:12:35
Name: START_DATE, Length: 19166, dtype: datetime64[ns]

In [104]:
p

,SCW_ID,SCW_VER,SCW_TYPE,RA_X,DEC_X,START_DATE,END_DATE,OBS_ID,OBS_TYPE,PS,PI_NAME,GOOD_SPI,GOOD_PICSIT,GOOD_ISGRI,GOOD_JEMX,GOOD_JEMX1,GOOD_JEMX2,GOOD_OMC,DSIZE,_SEARCH_OFFSET
0,001130000050,001,POINTING,299.543488,35.301971,2002-11-16 20:06:11,2002-11-16 20:16:53,...,,PUBLIC,...,575,0,0,571,571,571,575,13746176,6.444
1,001130000061,001,SLEW,299.567740,35.250057,2002-11-16 20:16:53,2002-11-16 20:18:23,...,,PUBLIC,...,89,1,12,75,74,75,90,3153920,3.111
2,001130000070,001,POINTING,299.590179,35.201195,2002-11-16 20:18:23,2002-11-16 20:55:43,00600030001 ...,CALIBRATION,PUBLIC,PUBLIC ...,1861,1815,1330,2221,2212,2221,2196,69844992,0.026
3,001130000080,001,POINTING,299.590179,35.201195,2002-11-16 20:55:43,2002-11-16 21:53:21,00600030001 ...,CALIBRATION,PUBLIC,PUBLIC ...,3455,3432,2161,3456,3456,2704,3458,117604352,0.026
4,001130000091,001,SLEW,300.101460,36.279747,2002-11-16 21:53:21,2002-11-16 21:55:17,00600030001 ...,CALIBRATION,PUBLIC,PUBLIC ...,116,0,72,116,116,0,0,4890624,69.312
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
19161,250300240010,001,POINTING,306.328033,35.514473,2022-05-16 13:17:35,2022-05-16 14:13:10,19200110001 ...,GENERAL,PRIVATE,PROF.\nJOERN\nWILMS ...,3297,3271,3296,3231,3231,3156,0,146329600,330.167
19162,250300240021,001,SLEW,307.154813,34.567347,2022-05-16 14:13:10,2022-05-16 14:15:05,19200110001 ...,GENERAL,PRIVATE,PROF.\nJOERN\nWILMS ...,114,0,115,113,113,0,0,5840896,374.160
19163,250300250010,001,POINTING,307.853790,33.744278,2022-05-16 14:15:05,2022-05-16 15:10:39,19200110001 ...,GENERAL,PRIVATE,PROF.\nJOERN\nWILMS ...,3274,3247,3273,3274,3274,3274,0,144752640,417.852
19164,250300250021,001,SLEW,307.185148,33.354976,2022-05-16 15:10:39,2022-05-16 15:12:35,19200110001 ...,GENERAL,PRIVATE,PROF.\nJOERN\nWILMS ...,115,0,116,116,116,114,0,6094848,392.383
19165,250300260010,001,POINTING,305.735168,32.485390,2022-05-16 15:12:35,2022-05-16 16:08:09,19200110001 ...,GENERAL,PRIVATE,PROF.\nJOERN\nWILMS ...,3276,3255,3275,3276,3276,3276,0,146124800,346.788

In [5]:
import pandas as pd
import numpy as np

In [6]:
a = np.random.rand(100)

In [7]:
a[a>0.5]

array([0.62234015, 0.51510374, 0.56693197, 0.85043499, 0.55142741,
       0.67132513, 0.86049707, 0.69141279, 0.55944578, 0.82677777,
       0.62234088, 0.51972122, 0.57078457, 0.68891545, 0.50052482,
       0.61841601, 0.5105579 , 0.66305097, 0.94402096, 0.74897383,
       0.90918926, 0.96279382, 0.79723449, 0.77915931, 0.77503766,
       0.62594516, 0.7706974 , 0.56663862, 0.81974844, 0.7079689 ,
       0.62538205, 0.68749091, 0.72640077, 0.98790525, 0.95772414,
       0.57751921, 0.89328979, 0.91629062, 0.71244089, 0.61590793,
       0.62955828, 0.76038255, 0.91476059, 0.70957898, 0.56868945,
       0.9427608 , 0.99546253, 0.61251427, 0.85089993, 0.90805542,
       0.56619208, 0.59674997])

In [8]:
heasarc = Heasarc()
table = heasarc.query_mission_list()
table.pprint()

   Mission    ...                Table Description
------------- ... -----------------------------------------------
CTASST1M-REV1 ...                                             Run
    FACT-REV1 ...                                             Run
INTEGRAL-REV3 ...                                       Proposals
INTEGRAL-REV3 ... Proposal Information and Observation Parameters
INTEGRAL-REV3 ...                       SCW - Science Window Data

In [9]:
table

<Table length=5>
   Mission    ...                Table Description
    str13     ...                      str47
------------- ... -----------------------------------------------
CTASST1M-REV1 ...                                             Run
    FACT-REV1 ...                                             Run
INTEGRAL-REV3 ...                                       Proposals
INTEGRAL-REV3 ... Proposal Information and Observation Parameters
INTEGRAL-REV3 ...                       SCW - Science Window Data

In [107]:
from astroquery.heasarc import Heasarc, Conf
import astropy.units as u
from astropy.coordinates import SkyCoord
import pandas as pd 
heasarc = Heasarc()
Conf.server.set('https://www.isdc.unige.ch/browse/w3query.pl')
mission = "integral_rev3_scw"
coords = SkyCoord('12h29m06.70s +02d03m08.7s', frame='icrs')
table = heasarc.query_region(position=coords, mission=mission, radius='1 degree', resultsmax=0)
table.convert_bytestring_to_unicode()
# convert from astropy table to pandas - easier to use
table = table.to_pandas()
table["SCW_VER"] = pd.to_numeric(table["SCW_VER"], errors="coerce")

WARNING: UnitsWarning: 'ISO' did not parse as fits unit: At col 0, Unit 'ISO' not supported by the FITS standard.  If this is meant to be a custom unit, define it with 'u.def_unit'. To have it recognized inside a file reader or other code, enable it with 'u.add_enabled_units'. For details, see https://docs.astropy.org/en/latest/units/combining_and_defining.html [astropy.units.core]

In [108]:
table

,SCW_ID,SCW_VER,SCW_TYPE,RA_X,DEC_X,START_DATE,END_DATE,OBS_ID,OBS_TYPE,PS,PI_NAME,GOOD_SPI,GOOD_PICSIT,GOOD_ISGRI,GOOD_JEMX,GOOD_JEMX1,GOOD_JEMX2,GOOD_OMC,DSIZE,_SEARCH_OFFSET
0,044400210021,1,SLEW,186.318164,2.016083,2006-06-03 00:55:17,2006-06-03 00:57:13,03999250001,GCDE,PUBLIC,ISWT,115,7,10,114,114,0,0,6247424,57.590
1,100300040021,1,SLEW,186.336723,1.904326,2010-12-30 14:59:39,2010-12-30 15:01:34,07200060002,GENERAL,PUBLIC,DR\nROLAND\nWALTER,114,104,115,20,0,20,0,3780608,57.133
2,112300300021,1,SLEW,186.347073,2.313033,2011-12-25 13:16:55,2011-12-25 13:18:50,08200140004,GENERAL,PUBLIC,DR\nROLAND\nWALTER,115,104,115,115,115,114,0,5779456,57.960
3,003200180021,1,SLEW,186.360459,2.249411,2003-01-17 17:53:23,2003-01-17 17:55:23,01200230008,GENERAL,PUBLIC,THIERRY\nCOURVOISIER,,,,,,,,5011456,56.264
4,002800210021,1,SLEW,186.385156,2.256269,2003-01-05 23:58:38,2003-01-06 00:00:38,01200230007,GENERAL,PUBLIC,THIERRY\nCOURVOISIER,120,0,104,117,0,117,0,5018624,54.908
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
269,119100320010,1,POINTING,188.199921,2.379528,2012-07-16 00:42:15,2012-07-16 01:32:15,09200100004,GENERAL,PUBLIC,DR\nROLAND\nWALTER,2996,2971,2992,2944,2944,2944,2970,99123200,58.660
270,118100460021,1,SLEW,188.204369,2.015947,2012-06-16 12:52:46,2012-06-16 12:54:58,09200100002,GENERAL,PUBLIC,DR\nROLAND\nWALTER,0,120,132,131,131,130,0,4026368,55.595
271,100500090021,1,SLEW,188.206634,2.424577,2011-01-05 19:42:39,2011-01-05 19:44:50,08200140001,GENERAL,PUBLIC,DR\nROLAND\nWALTER,130,120,131,130,130,129,0,4358144,59.991
272,003200420021,1,SLEW,188.208980,1.856685,2003-01-18 09:22:32,2003-01-18 09:24:33,01200230008,GENERAL,PUBLIC,THIERRY\nCOURVOISIER,,,,,,,,5017600,57.053
273,087800360021,1,SLEW,188.211399,2.009417,2009-12-23 04:13:36,2009-12-23 04:15:47,07200060001,GENERAL,PUBLIC,DR\nROLAND\nWALTER,130,128,131,129,0,129,0,7274496,56.033